---
name: Build/Publish ORT CI Action image
# 1) Builds base image from the ORT repo
# 2) Builds base CI image with Dockerfile (file from the ORT GitLab CI project)
# 3) Finally, builds the ORT CI Action image

on: [workflow_call, workflow_dispatch] # yamllint disable-line rule:truthy

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_BASE: ort-base
  IMAGE_NAME_CI: ort-ci-base
  IMAGE_NAME_ACTION: ort-ci-action

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    if: github.ref_name == 'feature/clean-up-input' || github.ref_name == 'main'
    steps:
      - name: Checkout Actions repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Checkout ORT repo
        uses: actions/checkout@v3
        with:
          repository: oss-review-toolkit/ort
          path: ort

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the ORT Base Image
      - name: Extract metadata (tags, labels) for ort base image
        id: ort_base_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_BASE }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{branch}},priority=1,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=tag,priority=2
            type=raw,value=${{ env.IMAGE_NAME_BASE }}-{{branch}}-{{date 'YYYYMMDD'}}-{{sha}},priority=31,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ env.IMAGE_NAME_BASE }}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}},priority=32, enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push ort base image
        uses: docker/build-push-action@v2
        with:
          context: ort/
          push: true
          tags: ${{ steps.ort_base_meta.outputs.tags }}
          labels: ${{ steps.ort_base_meta.outputs.labels }}

      # Build the ORT CI Base Image based on the Base Image
      - name: Extract metadata (tags, labels) for ort ci image
        id: ort_ci_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_CI }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{branch}},priority=1,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=tag,priority=2
            type=raw,value=${{ env.IMAGE_NAME_CI }}-{{branch}}-{{date 'YYYYMMDD'}}-{{sha}},priority=31,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ env.IMAGE_NAME_CI }}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}},priority=32, enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push ort ci image
        uses: docker/build-push-action@v2
        with:
          context: https://github.com/oss-review-toolkit/ort-ci-base.git
          file: /docker/Dockerfile.ci
          push: true
          tags: ${{ steps.ort_ci_meta.outputs.tags }}
          labels: ${{ steps.ort_ci_meta.outputs.labels }}
          build-args: |
            ORT_DOCKER_IMAGE=${{ fromJSON(steps.ort_base_meta.outputs.json).tags[0] }}

      # Finally build the Action image
      - name: Extract metadata (tags, labels) for ort action image
        id: ort_action_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_ACTION }}
          flavor: |
            latest=true
          tags: |
            type=raw,value={{branch}},priority=1,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=ref,event=tag,priority=2
            type=raw,value=${{ env.IMAGE_NAME_ACTION }}-{{branch}}-{{date 'YYYYMMDD'}}-{{sha}},priority=31,enable=${{ !startsWith(github.ref, 'refs/tags/v') }}
            type=raw,value=${{ env.IMAGE_NAME_ACTION }}-{{tag}}-{{date 'YYYYMMDD'}}-{{sha}},priority=32, enable=${{ startsWith(github.ref, 'refs/tags/v') }}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=semver,pattern={{version}}
            type=sha
            type=sha,format=long

      - name: Build and push ort action image
        id: docker_action_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.ort_action_meta.outputs.tags }}
          labels: ${{ steps.ort_action_meta.outputs.labels }}
          build-args: |
            BASEIMAGE=${{ fromJSON(steps.ort_ci_meta.outputs.json).tags[0] }}

#BASEIMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_CI }}
